---
title: "Gamification BDA"
execute: 
  echo: false
---

## Introduction

TBA

- **G**: Gamification approach was used; value = {true, false}
- **EJ**: Experience in Java; value = {"<1 year", "1-3 years", ">3 years"}
- **EW**: Experience in web development; value = {"<1 year", "1-3 years", ">3 years"}
- **ET**: Experience in software testing; value = {"<1 year", "1-3 years", ">3 years"}
- **W**: Inspected widgets
- **B**: Identified bugs
- **COV**: Test coverage
- **EF**: Effectiveness of exploratory testing
- **AW**: Average number of widgets on a page

```{r}
suppressPackageStartupMessages(library(dagitty))
suppressPackageStartupMessages(library(rethinking))
dag <- dagitty("dag {
G -> W
G -> B
EJ -> W
EJ -> B
EW -> W
EW -> B
ET -> W
ET -> B
W -> COV
B -> COV
AW -> COV
COV -> EF
}")
drawdag(dag)
```

Assumptions:

- G -\> W: Using Gamification encourage testers to inspect more widgets
- G -\> B: Using Gamification encourage testers to identify more bugs
- EJ -\> W: Experience in the used programming language will improves the inspection rate of widgets
- EJ -\> B: Experience in the used programming will identify more bugs
- EW -\> W: Experience in the technology of the SUT improves the inspection rate of widgets
- EW -\> B: Experience in the technology of the SUT improves the identification of bugs
- ET -\> W: Experience in software testing improves the inspection rate of widgets
- ET -\> B: Experience in software testing improves the identification of bugs
- W -\> COV: More inspected widgets increase the test coverage
- B -\> COV: More identified bugs increase the test coverage
- AW -\> COV: Average number of widgets on a page influence the test coverage of exploratory tests
- COV -\> EF: More test coverage improves the effectiveness of exploratory tests
